export const EVENTS_TRANSACTION = 'EVENTS_TRANSACTION'
export const EVENTS_VERSION_SET = 'EVENTS_VERSION_SET'
export const EVENTS_TRADES_ADD = 'EVENTS_TRADES_ADD'
export const EVENTS_INFOS_ADD = 'EVENTS_INFOS_ADD'
