export const EVENTS_TRANSACTION = 'EVENTS_TRANSACTION'
export const EVENTS_VERSION_SET = 'EVENTS_VERSION_SET'
export const EVENTS_PERFORMANCE_SET = 'EVENTS_PERFORMANCE_SET'
export const EVENTS_CONFIG_SET = 'EVENTS_CONFIG_SET'

export const EVENTS_TRADE_ADD = 'EVENTS_TRADE_ADD'
export const EVENTS_INFO_ADD = 'EVENTS_INFO_ADD'
export const EVENTS_ERROR_ADD = 'EVENTS_ERROR_ADD'
export const EVENTS_ORDER_ADD = 'EVENTS_ORDER_ADD'
export const EVENTS_MISC_ADD = 'EVENTS_MISC_ADD'
export const EVENTS_PRICE_ADD = 'EVENTS_PRICE_ADD'
export const EVENTS_LOG_ADD = 'EVENTS_LOG_ADD'

export const EVENTS_LAST_EVENT_TIME_SET = 'EVENTS_LAST_EVENT_TIME_SET'
