export const EVENTS_TRADES_ADD = 'EVENTS_TRADES_ADD'
export const EVENTS_TRADES_SET = 'EVENTS_TRADES_SET'
export const EVENTS_INFOS_ADD = 'EVENTS_INFOS_ADD'
export const EVENTS_INFOS_SET = 'EVENTS_INFOS_SET'
